version: "3"

services:
  chat-service-db:
    image: mysql:5.7.20
    container_name: chat-service-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
    ports:
      - 7200:3306
    volumes:
      - chat-service-db-volume:/var/lib/mysql

  users-service-db:
    image: mysql:5.7.20
    container_name: users-service-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
    ports:
      - 7201:3306
    volumes:
      - users-service-db-volume:/var/lib/mysql

  chat-service:
    build:
      context: ./chat-service
    volumes:
      - ./chat-service:/chat-service/
      - /chat-service/node_modules
    ports:
      - 7100:7100
    depends_on:
      - chat-service-db

  users-service:
    build:
      context: ./users-service
    volumes:
      - ./users-service:/users-service/
      - /users-service/node_modules
    ports:
      - 7101:7101
    depends_on:
      - users-service-db

  api-gateway:
    build:
      context: ./api-gateway
    volumes:
      - ./api-gateway:/api-gateway/
      - /api-gateway/node_modules
    ports:
      - 7000:7000
    depends_on:
      - chat-service
      - users-service

  chat-app:
    build:
      context: ./chat-app
    env_file: ./chat-app/.env
    volumes:
      - ./chat-app:/chat-app/
      - /chat-app/node_modules
    ports:
      - 7001:7001
    depends_on:
      - api-gateway

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "7300:80"
    links:
      - users-service-db
      - chat-service-db
    depends_on:
      - users-service-db
      - chat-service-db
    volumes:
      - ./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php

volumes:
  chat-service-db-volume:
  users-service-db-volume:
